[project]
name = "flask-ai-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "asgiref>=3.7.2",
    "flask>=2.2.5",
    "numpy>=1.21.6",
    "opencv-python>=4.11.0.86",
    "pillow>=9.5.0",
]
